-- RIK-1: Rikuna MVP schema (v3)
-- Source of truth: specs/RIKUNA-PRD-schema-basedatos-rikuna.md, Sections 2-7.
-- Do not edit this file for future schema changes; add a new timestamped migration instead.

-- ---------------------------------------------------------------------------
-- Shared trigger function: keeps updated_at current on UPDATE.
-- Referenced by name (public.handle_updated_at) from Sections 2.1, 4 and 5 of
-- the schema doc, but never defined there.
-- ---------------------------------------------------------------------------
create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- 2.1 media_items
-- ---------------------------------------------------------------------------
create table if not exists public.media_items (
    id              uuid        default gen_random_uuid() not null primary key,
    created_at      timestamptz default now() not null,
    updated_at      timestamptz default now() not null,

    imdb_id         varchar not null,          -- tconst, ej. "tt0111161" — identificador universal
    tmdb_id         integer,

    type            varchar not null,          -- 'movie' | 'tv'
    title_type      varchar,                   -- valor crudo de IMDb: movie, tvSeries, tvMiniSeries, short, tvMovie
    title           varchar not null,
    original_title  varchar,
    slug            varchar not null,
    year            integer,
    end_year        integer,
    runtime_minutes integer,
    description     text,
    poster_url      text,
    content_rating  varchar,                   -- clasificación por edad; NO es la calificación de IMDb

    imdb_rating     numeric(3,1),
    imdb_votes      integer,
    imdb_url        text,

    -- Control de completitud
    is_stub         boolean default false not null,  -- creado desde CSV, faltan poster/sinopsis/elenco
    enriched_at     timestamptz,

    metadata        jsonb default '{}'::jsonb not null,

    constraint media_items_imdb_id_uq unique (imdb_id),
    constraint media_items_slug_uq unique (slug)
);

create index if not exists media_items_type_idx on public.media_items (type);
create index if not exists media_items_rating_idx on public.media_items (imdb_rating desc nulls last);
create index if not exists media_items_stub_idx on public.media_items (is_stub) where is_stub;

create or replace trigger media_items_updated_at
    before update on public.media_items
    for each row execute function public.handle_updated_at();

-- ---------------------------------------------------------------------------
-- 2.2 Géneros y personas
-- ---------------------------------------------------------------------------
create table if not exists public.genres (
    id   uuid default gen_random_uuid() not null primary key,
    name varchar not null,
    slug varchar not null unique
);

create table if not exists public.media_genres (
    media_id uuid not null references public.media_items(id) on delete cascade,
    genre_id uuid not null references public.genres(id) on delete cascade,
    primary key (media_id, genre_id)
);
create index if not exists media_genres_genre_idx on public.media_genres (genre_id);

create table if not exists public.people (
    id      uuid default gen_random_uuid() not null primary key,
    imdb_id varchar unique,     -- nconst
    name    varchar not null,
    photo_url text
);

create table if not exists public.media_people (
    media_id       uuid not null references public.media_items(id) on delete cascade,
    person_id      uuid not null references public.people(id) on delete cascade,
    role           varchar not null,   -- 'actor' | 'director' | 'writer' | 'creator'
    character_name varchar,
    sort_order     integer default 0 not null,
    primary key (media_id, person_id, role)
);
create index if not exists media_people_media_idx on public.media_people (media_id, sort_order);

-- Note: seasons / episodes are explicitly out of MVP scope (schema doc Section 2.3).

-- ---------------------------------------------------------------------------
-- 3.1 platforms
-- ---------------------------------------------------------------------------
create table if not exists public.platforms (
    id                uuid default gen_random_uuid() not null primary key,
    name              varchar not null,          -- "Apple TV+"
    slug              varchar not null unique,   -- "apple-tv-plus"
    logo_url          text,
    provider_id_movie integer,   -- ids que ya trae tu proceso externo en metadata
    provider_id_tv    integer
);

-- ---------------------------------------------------------------------------
-- 3.2 catalog_snapshots — cada archivo cargado del proceso externo
-- ---------------------------------------------------------------------------
create table if not exists public.catalog_snapshots (
    id           uuid default gen_random_uuid() not null primary key,
    created_at   timestamptz default now() not null,
    platform_id  uuid not null references public.platforms(id) on delete cascade,
    country      varchar(2) not null,          -- "BO"
    generated_at timestamptz not null,         -- metadata.generated_at del archivo
    source_file  varchar,                      -- "apple-tv-plus_BO.json"
    total_items  integer default 0 not null,
    status       varchar default 'pending' not null  -- 'pending' | 'completed' | 'failed'
);

create index if not exists catalog_snapshots_platform_idx
    on public.catalog_snapshots (platform_id, country, generated_at desc);

-- ---------------------------------------------------------------------------
-- 3.3 media_availability — dónde está disponible cada título (DDL only)
-- ---------------------------------------------------------------------------
create table if not exists public.media_availability (
    id               uuid default gen_random_uuid() not null primary key,
    media_id         uuid not null references public.media_items(id) on delete cascade,
    platform_id      uuid not null references public.platforms(id) on delete cascade,
    country          varchar(2) not null,
    url              text,                  -- enlace directo si existe; si no, página del servicio
    offer_type       varchar default 'subscription' not null,  -- 'subscription' | 'rent' | 'buy'

    is_available     boolean default true not null,
    first_seen_at    timestamptz default now() not null,
    last_seen_at     timestamptz default now() not null,
    last_snapshot_id uuid references public.catalog_snapshots(id),

    constraint media_availability_uq unique (media_id, platform_id, country, offer_type)
);

create index if not exists media_availability_lookup_idx
    on public.media_availability (platform_id, country, is_available);
create index if not exists media_availability_media_idx
    on public.media_availability (media_id) where is_available;

-- ---------------------------------------------------------------------------
-- 4. user_subscriptions
-- ---------------------------------------------------------------------------
create table if not exists public.user_subscriptions (
    id          uuid default gen_random_uuid() not null primary key,
    created_at  timestamptz default now() not null,
    updated_at  timestamptz default now() not null,
    user_id     uuid not null references auth.users(id) on delete cascade,
    platform_id uuid not null references public.platforms(id) on delete restrict,
    country     varchar(2) not null,
    started_on  date not null default current_date,
    ended_on    date,                              -- null = vigente
    notes       text
);

-- Puedes tener varias activas a la vez (si pagas dos servicios), pero no
-- dos filas abiertas para la misma plataforma+país
create unique index if not exists user_subscriptions_active_uq
    on public.user_subscriptions (user_id, platform_id, country)
    where ended_on is null;

create index if not exists user_subscriptions_active_idx
    on public.user_subscriptions (user_id) where ended_on is null;

create or replace trigger user_subscriptions_updated_at
    before update on public.user_subscriptions
    for each row execute function public.handle_updated_at();

-- ---------------------------------------------------------------------------
-- 5. user_media_status
-- ---------------------------------------------------------------------------
create table if not exists public.user_media_status (
    id                uuid default gen_random_uuid() not null primary key,
    created_at        timestamptz default now() not null,
    updated_at        timestamptz default now() not null,
    user_id           uuid not null references auth.users(id) on delete cascade,
    media_id          uuid not null references public.media_items(id) on delete cascade,

    watched           boolean default false not null,
    watched_at        timestamptz,          -- "Date Rated" del CSV de calificaciones
    personal_rating   smallint,             -- "Your Rating" (1-10)

    want_to_watch     boolean default false not null,   -- viene de la lista de seguimiento de IMDb
    want_added_at     timestamptz,

    dismissed         boolean default false not null,   -- "no me interesa" — se excluye de recomendaciones

    source            varchar default 'manual' not null, -- 'manual' | 'imdb_ratings' | 'imdb_watchlist'
    manually_edited   boolean default false not null,    -- protege contra sobrescritura al reimportar

    constraint user_media_status_uq unique (user_id, media_id),
    constraint user_media_status_rating_chk check (personal_rating between 1 and 10)
);

create index if not exists ums_user_watched_idx on public.user_media_status (user_id, watched);
create index if not exists ums_user_want_idx on public.user_media_status (user_id, want_to_watch) where want_to_watch;

create or replace trigger user_media_status_updated_at
    before update on public.user_media_status
    for each row execute function public.handle_updated_at();

-- ---------------------------------------------------------------------------
-- 6. user_lists + list_items
-- ---------------------------------------------------------------------------
create table if not exists public.user_lists (
    id          uuid default gen_random_uuid() not null primary key,
    created_at  timestamptz default now() not null,
    updated_at  timestamptz default now() not null,
    user_id     uuid not null references auth.users(id) on delete cascade,
    name        varchar not null,
    slug        varchar not null,
    description text,
    is_public   boolean default false not null,   -- false = solo el dueño la ve; true = visible por enlace, incluso sin sesión (ver Sección 9.2)
    constraint user_lists_user_slug_uq unique (user_id, slug)
);

create table if not exists public.list_items (
    id         uuid default gen_random_uuid() not null primary key,
    created_at timestamptz default now() not null,
    list_id    uuid not null references public.user_lists(id) on delete cascade,
    media_id   uuid not null references public.media_items(id) on delete cascade,
    sort_order integer default 0 not null,
    note       text,
    constraint list_items_uq unique (list_id, media_id)
);
create index if not exists list_items_list_idx on public.list_items (list_id, sort_order);

create or replace trigger user_lists_updated_at
    before update on public.user_lists
    for each row execute function public.handle_updated_at();

-- ---------------------------------------------------------------------------
-- 7.1 imdb_import_batches + imdb_import_rows
-- ---------------------------------------------------------------------------
create table if not exists public.imdb_import_batches (
    id             uuid default gen_random_uuid() not null primary key,
    created_at     timestamptz default now() not null,
    user_id        uuid not null references auth.users(id) on delete cascade,
    source_type    varchar not null,   -- 'ratings' | 'watchlist'
    file_name      varchar,
    status         varchar default 'pending' not null,
    total_rows     integer default 0 not null,
    matched_rows   integer default 0 not null,  -- ya existían en el catálogo
    created_rows   integer default 0 not null,  -- se crearon como stub
    skipped_rows   integer default 0 not null,
    completed_at   timestamptz
);
create index if not exists imdb_batches_user_idx on public.imdb_import_batches (user_id, created_at desc);

create table if not exists public.imdb_import_rows (
    id          uuid default gen_random_uuid() not null primary key,
    batch_id    uuid not null references public.imdb_import_batches(id) on delete cascade,
    imdb_id     varchar not null,     -- columna "Const"
    title       varchar,
    title_type  varchar,              -- columna "Title Type"
    year        integer,
    your_rating smallint,             -- solo en export de calificaciones
    date_rated  date,
    media_id    uuid references public.media_items(id),
    result      varchar default 'pending' not null  -- 'matched' | 'created' | 'skipped'
);
create index if not exists imdb_rows_batch_idx on public.imdb_import_rows (batch_id);
